import turtle
t1=turtle.Turtle()
t2=turtle.Turtle()
t3=turtle.Turtle()
t4=turtle.Turtle()
t5=turtle.Turtle()
t1.shape("turtle")
t2.shape("turtle")
t3.shape("turtle")
t4.shape("turtle")
t5.shape("turtle")

t1.penup()
t1.goto(-150,50)
t1.pencolor("blue")
t1.pensize(5)
t1.pendown()
t1.write("   유럽")
t1.hideturtle()
t1.circle(50)

t2.penup()
t2.goto(-30,50)
t2.pencolor("black")
t2.pensize(5)
t2.pendown()
t2.write("   아프리카")
t2.hideturtle()
t2.circle(50)

t3.penup()
t3.goto(90,50)
t3.pencolor("red")
t3.pensize(5)
t3.pendown()
t3.write("   아메리카")
t3.hideturtle()
t3.circle(50)

t4.penup()
t4.goto(-90,10)
t4.pencolor("yellow")
t4.pensize(5)
t4.pendown()
t4.write("   아시아")
t4.hideturtle()
t4.circle(50)

t5.penup()
t5.goto(40,10)
t5.pencolor("green")
t5.pensize(5)
t5.pendown()
t5.write("   오세아니아")
t5.hideturtle()
t5.circle(50)
turtle.done()